//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18051
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gitter.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gitter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to open repository.
        /// </summary>
        internal static string ErrFailedToOpenRepository {
            get {
                return ResourceManager.GetString("ErrFailedToOpenRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid path.
        /// </summary>
        internal static string ErrInvalidPath {
            get {
                return ResourceManager.GetString("ErrInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path cannot be empty.
        /// </summary>
        internal static string ErrPathCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrPathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;{0}&apos; is not a valid repository..
        /// </summary>
        internal static string ErrPathIsNotValidRepository {
            get {
                return ResourceManager.GetString("ErrPathIsNotValidRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specified path is not a valid repository.
        /// </summary>
        internal static string ErrSpecifiedPathIsNotValidRepository {
            get {
                return ResourceManager.GetString("ErrSpecifiedPathIsNotValidRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepoAddMedium {
            get {
                object obj = ResourceManager.GetObject("ImgRepoAddMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepoCloneMedium {
            get {
                object obj = ResourceManager.GetObject("ImgRepoCloneMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepoInitMedium {
            get {
                object obj = ResourceManager.GetObject("ImgRepoInitMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepoScanMedium {
            get {
                object obj = ResourceManager.GetObject("ImgRepoScanMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositories {
            get {
                object obj = ResourceManager.GetObject("ImgRepositories", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepository {
            get {
                object obj = ResourceManager.GetObject("ImgRepository", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositoryAdd {
            get {
                object obj = ResourceManager.GetObject("ImgRepositoryAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositoryExplorer {
            get {
                object obj = ResourceManager.GetObject("ImgRepositoryExplorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositoryLarge {
            get {
                object obj = ResourceManager.GetObject("ImgRepositoryLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositoryOpen {
            get {
                object obj = ResourceManager.GetObject("ImgRepositoryOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositoryRemove {
            get {
                object obj = ResourceManager.GetObject("ImgRepositoryRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStartPage {
            get {
                object obj = ResourceManager.GetObject("ImgStartPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStartPageLogo {
            get {
                object obj = ResourceManager.GetObject("ImgStartPageLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStartPageLogoDark {
            get {
                object obj = ResourceManager.GetObject("ImgStartPageLogoDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStartPageLogoGradient {
            get {
                object obj = ResourceManager.GetObject("ImgStartPageLogoGradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStartPageLogoGradientDark {
            get {
                object obj = ResourceManager.GetObject("ImgStartPageLogoGradientDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string StrAbout {
            get {
                return ResourceManager.GetString("StrAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string StrAdd {
            get {
                return ResourceManager.GetString("StrAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Local Repository....
        /// </summary>
        internal static string StrAddLocalRepository {
            get {
                return ResourceManager.GetString("StrAddLocalRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Repository.
        /// </summary>
        internal static string StrAddRepository {
            get {
                return ResourceManager.GetString("StrAddRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Service.
        /// </summary>
        internal static string StrAddService {
            get {
                return ResourceManager.GetString("StrAddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clone Remote Repository....
        /// </summary>
        internal static string StrCloneRemoteRepository {
            get {
                return ResourceManager.GetString("StrCloneRemoteRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close page after repository load.
        /// </summary>
        internal static string StrClosePageAfterRepositoryLoad {
            get {
                return ResourceManager.GetString("StrClosePageAfterRepositoryLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        internal static string StrDate {
            get {
                return ResourceManager.GetString("StrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string StrDescription {
            get {
                return ResourceManager.GetString("StrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string StrEmail {
            get {
                return ResourceManager.GetString("StrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string StrExit {
            get {
                return ResourceManager.GetString("StrExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string StrHelp {
            get {
                return ResourceManager.GetString("StrHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Init Local Repository....
        /// </summary>
        internal static string StrInitLocalRepository {
            get {
                return ResourceManager.GetString("StrInitLocalRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no available.
        /// </summary>
        internal static string StrlNoAvailable {
            get {
                return ResourceManager.GetString("StrlNoAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на none.
        /// </summary>
        internal static string StrlNone {
            get {
                return ResourceManager.GetString("StrlNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local Repositories.
        /// </summary>
        internal static string StrLocalRepositories {
            get {
                return ResourceManager.GetString("StrLocalRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No repositories found.
        /// </summary>
        internal static string StrNoRepositoriesFound {
            get {
                return ResourceManager.GetString("StrNoRepositoriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string StrOpen {
            get {
                return ResourceManager.GetString("StrOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Command Line.
        /// </summary>
        internal static string StrOpenCommandLine {
            get {
                return ResourceManager.GetString("StrOpenCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in Windows Explorer.
        /// </summary>
        internal static string StrOpenInWindowsExplorer {
            get {
                return ResourceManager.GetString("StrOpenInWindowsExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        internal static string StrOptions {
            get {
                return ResourceManager.GetString("StrOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path.
        /// </summary>
        internal static string StrPath {
            get {
                return ResourceManager.GetString("StrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent.
        /// </summary>
        internal static string StrRecent {
            get {
                return ResourceManager.GetString("StrRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent repositories.
        /// </summary>
        internal static string StrRecentRepositories {
            get {
                return ResourceManager.GetString("StrRecentRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove From List.
        /// </summary>
        internal static string StrRemoveRepository {
            get {
                return ResourceManager.GetString("StrRemoveRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repositories.
        /// </summary>
        internal static string StrRepositories {
            get {
                return ResourceManager.GetString("StrRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repository.
        /// </summary>
        internal static string StrRepository {
            get {
                return ResourceManager.GetString("StrRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repository Explorer.
        /// </summary>
        internal static string StrRepositoryExplorer {
            get {
                return ResourceManager.GetString("StrRepositoryExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan Local Repositories....
        /// </summary>
        internal static string StrScanLocalRepository {
            get {
                return ResourceManager.GetString("StrScanLocalRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check failed.
        /// </summary>
        internal static string StrsCheckFailed {
            get {
                return ResourceManager.GetString("StrsCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking for updates.
        /// </summary>
        internal static string StrsCheckingForUpdates {
            get {
                return ResourceManager.GetString("StrsCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show page on startup.
        /// </summary>
        internal static string StrShowPageOnStartup {
            get {
                return ResourceManager.GetString("StrShowPageOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        internal static string StrSize {
            get {
                return ResourceManager.GetString("StrSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Page.
        /// </summary>
        internal static string StrStartPage {
            get {
                return ResourceManager.GetString("StrStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на v{0} is available.
        /// </summary>
        internal static string StrsVersionIsAvailable {
            get {
                return ResourceManager.GetString("StrsVersionIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your version is up to date.
        /// </summary>
        internal static string StrsYourVersionIsUpToDate {
            get {
                return ResourceManager.GetString("StrsYourVersionIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toolbars.
        /// </summary>
        internal static string StrToolbars {
            get {
                return ResourceManager.GetString("StrToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        internal static string StrTools {
            get {
                return ResourceManager.GetString("StrTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string StrType {
            get {
                return ResourceManager.GetString("StrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Url.
        /// </summary>
        internal static string StrUrl {
            get {
                return ResourceManager.GetString("StrUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        internal static string StrVersion {
            get {
                return ResourceManager.GetString("StrVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        internal static string StrView {
            get {
                return ResourceManager.GetString("StrView", resourceCulture);
            }
        }
    }
}
