//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18051
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gitter.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gitter.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to execute some actions.
        /// </summary>
        internal static string ErrFailedToRunElevatedProcess {
            get {
                return ResourceManager.GetString("ErrFailedToRunElevatedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some options could not be applied because gitter was uable to start an elevated process..
        /// </summary>
        internal static string ErrSomeOptionsCouldNotBeApplied {
            get {
                return ResourceManager.GetString("ErrSomeOptionsCouldNotBeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoApplication {
            get {
                object obj = ResourceManager.GetObject("IcoApplication", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoApplicationTerminal {
            get {
                object obj = ResourceManager.GetObject("IcoApplicationTerminal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocument {
            get {
                object obj = ResourceManager.GetObject("IcoDocument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentAccess {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentAccess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentBinary {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentBinary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentCode {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentCode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentExcel {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentExcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentExcelCsv {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentExcelCsv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentFilm {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentFilm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentFlashMovie {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentFlashMovie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentGlobe {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentGlobe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentImage {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentMusic {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentMusic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentOffice {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentOffice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentOutlook {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentOutlook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentPdf {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentPdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentPhotoshop {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentPhotoshop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentPhp {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentPhp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentPowerpoint {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentPowerpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentText {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentVisualStudio {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentVisualStudio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentWord {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentWord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoDocumentXaml {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentXaml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgAction {
            get {
                object obj = ResourceManager.GetObject("ImgAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgActionHover {
            get {
                object obj = ResourceManager.GetObject("ImgActionHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgChecked {
            get {
                object obj = ResourceManager.GetObject("ImgChecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgCheckedHover {
            get {
                object obj = ResourceManager.GetObject("ImgCheckedHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgCheckIndeterminate {
            get {
                object obj = ResourceManager.GetObject("ImgCheckIndeterminate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgCheckIndeterminateHover {
            get {
                object obj = ResourceManager.GetObject("ImgCheckIndeterminateHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgChevronCollapse {
            get {
                object obj = ResourceManager.GetObject("ImgChevronCollapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgChevronCollapseHover {
            get {
                object obj = ResourceManager.GetObject("ImgChevronCollapseHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgChevronExpand {
            get {
                object obj = ResourceManager.GetObject("ImgChevronExpand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgChevronExpandHover {
            get {
                object obj = ResourceManager.GetObject("ImgChevronExpandHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgColumnExtender {
            get {
                object obj = ResourceManager.GetObject("ImgColumnExtender", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgFolder {
            get {
                object obj = ResourceManager.GetObject("ImgFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgGoBack {
            get {
                object obj = ResourceManager.GetObject("ImgGoBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgGoForward {
            get {
                object obj = ResourceManager.GetObject("ImgGoForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgGravatar {
            get {
                object obj = ResourceManager.GetObject("ImgGravatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgLog {
            get {
                object obj = ResourceManager.GetObject("ImgLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgLogDebug {
            get {
                object obj = ResourceManager.GetObject("ImgLogDebug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgLogError {
            get {
                object obj = ResourceManager.GetObject("ImgLogError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgLogInfo {
            get {
                object obj = ResourceManager.GetObject("ImgLogInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgLogWarning {
            get {
                object obj = ResourceManager.GetObject("ImgLogWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgMaximize {
            get {
                object obj = ResourceManager.GetObject("ImgMaximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgMenuCheck {
            get {
                object obj = ResourceManager.GetObject("ImgMenuCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgMinus {
            get {
                object obj = ResourceManager.GetObject("ImgMinus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgMinusHovered {
            get {
                object obj = ResourceManager.GetObject("ImgMinusHovered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgNormalize {
            get {
                object obj = ResourceManager.GetObject("ImgNormalize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgPlus {
            get {
                object obj = ResourceManager.GetObject("ImgPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgPlusHovered {
            get {
                object obj = ResourceManager.GetObject("ImgPlusHovered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgTabMenu {
            get {
                object obj = ResourceManager.GetObject("ImgTabMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgTabMenuExtends {
            get {
                object obj = ResourceManager.GetObject("ImgTabMenuExtends", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgTabScrollLeft {
            get {
                object obj = ResourceManager.GetObject("ImgTabScrollLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgTabScrollRight {
            get {
                object obj = ResourceManager.GetObject("ImgTabScrollRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgUnchecked {
            get {
                object obj = ResourceManager.GetObject("ImgUnchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgUncheckedHover {
            get {
                object obj = ResourceManager.GetObject("ImgUncheckedHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgViewHostClose {
            get {
                object obj = ResourceManager.GetObject("ImgViewHostClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgViewHostMenu {
            get {
                object obj = ResourceManager.GetObject("ImgViewHostMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgViewHostPin {
            get {
                object obj = ResourceManager.GetObject("ImgViewHostPin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgWebBrowser {
            get {
                object obj = ResourceManager.GetObject("ImgWebBrowser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Abort.
        /// </summary>
        internal static string StrAbort {
            get {
                return ResourceManager.GetString("StrAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}:.
        /// </summary>
        internal static string StrAddColon {
            get {
                return ResourceManager.GetString("StrAddColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0},.
        /// </summary>
        internal static string StrAddComma {
            get {
                return ResourceManager.GetString("StrAddComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}....
        /// </summary>
        internal static string StrAddEllipsis {
            get {
                return ResourceManager.GetString("StrAddEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}..
        /// </summary>
        internal static string StrAddPeriod {
            get {
                return ResourceManager.GetString("StrAddPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advanced.
        /// </summary>
        internal static string StrAdvanced {
            get {
                return ResourceManager.GetString("StrAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AntiAlias.
        /// </summary>
        internal static string StrAntiAlias {
            get {
                return ResourceManager.GetString("StrAntiAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appearance.
        /// </summary>
        internal static string StrAppearance {
            get {
                return ResourceManager.GetString("StrAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application Mode.
        /// </summary>
        internal static string StrApplicationMode {
            get {
                return ResourceManager.GetString("StrApplicationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application must be restarted to apply changes.
        /// </summary>
        internal static string StrApplicationMustBeRestartedToApply {
            get {
                return ResourceManager.GetString("StrApplicationMustBeRestartedToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        internal static string StrApply {
            get {
                return ResourceManager.GetString("StrApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        internal static string StrBack {
            get {
                return ResourceManager.GetString("StrBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Behavior.
        /// </summary>
        internal static string StrBehavior {
            get {
                return ResourceManager.GetString("StrBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bold.
        /// </summary>
        internal static string StrBold {
            get {
                return ResourceManager.GetString("StrBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom.
        /// </summary>
        internal static string StrBottom {
            get {
                return ResourceManager.GetString("StrBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string StrCancel {
            get {
                return ResourceManager.GetString("StrCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ClearType.
        /// </summary>
        internal static string StrClearType {
            get {
                return ResourceManager.GetString("StrClearType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string StrClose {
            get {
                return ResourceManager.GetString("StrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Colors.
        /// </summary>
        internal static string StrColors {
            get {
                return ResourceManager.GetString("StrColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Columns.
        /// </summary>
        internal static string StrColumns {
            get {
                return ResourceManager.GetString("StrColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contrast.
        /// </summary>
        internal static string StrContrast {
            get {
                return ResourceManager.GetString("StrContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy to Clipboard.
        /// </summary>
        internal static string StrCopyToClipboard {
            get {
                return ResourceManager.GetString("StrCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        internal static string StrDate {
            get {
                return ResourceManager.GetString("StrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date Format.
        /// </summary>
        internal static string StrDateFormat {
            get {
                return ResourceManager.GetString("StrDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        internal static string StrDefaultFormat {
            get {
                return ResourceManager.GetString("StrDefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Down.
        /// </summary>
        internal static string StrDown {
            get {
                return ResourceManager.GetString("StrDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string StrError {
            get {
                return ResourceManager.GetString("StrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Essential.
        /// </summary>
        internal static string StrEssential {
            get {
                return ResourceManager.GetString("StrEssential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Example.
        /// </summary>
        internal static string StrExample {
            get {
                return ResourceManager.GetString("StrExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exception.
        /// </summary>
        internal static string StrException {
            get {
                return ResourceManager.GetString("StrException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Family.
        /// </summary>
        internal static string StrFamily {
            get {
                return ResourceManager.GetString("StrFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font.
        /// </summary>
        internal static string StrFont {
            get {
                return ResourceManager.GetString("StrFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fonts.
        /// </summary>
        internal static string StrFonts {
            get {
                return ResourceManager.GetString("StrFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forward.
        /// </summary>
        internal static string StrForward {
            get {
                return ResourceManager.GetString("StrForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide.
        /// </summary>
        internal static string StrHide {
            get {
                return ResourceManager.GetString("StrHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ignore.
        /// </summary>
        internal static string StrIgnore {
            get {
                return ResourceManager.GetString("StrIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input Font.
        /// </summary>
        internal static string StrInputFont {
            get {
                return ResourceManager.GetString("StrInputFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Integration.
        /// </summary>
        internal static string StrIntegration {
            get {
                return ResourceManager.GetString("StrIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ISO 8601.
        /// </summary>
        internal static string StrISO8601 {
            get {
                return ResourceManager.GetString("StrISO8601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Italic.
        /// </summary>
        internal static string StrItalic {
            get {
                return ResourceManager.GetString("StrItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left Edge.
        /// </summary>
        internal static string StrLeftEdge {
            get {
                return ResourceManager.GetString("StrLeftEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log.
        /// </summary>
        internal static string StrLog {
            get {
                return ResourceManager.GetString("StrLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        internal static string StrMessage {
            get {
                return ResourceManager.GetString("StrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        internal static string StrNo {
            get {
                return ResourceManager.GetString("StrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string StrOk {
            get {
                return ResourceManager.GetString("StrOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        internal static string StrOptions {
            get {
                return ResourceManager.GetString("StrOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page Down.
        /// </summary>
        internal static string StrPageDown {
            get {
                return ResourceManager.GetString("StrPageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page Left.
        /// </summary>
        internal static string StrPageLeft {
            get {
                return ResourceManager.GetString("StrPageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page Right.
        /// </summary>
        internal static string StrPageRight {
            get {
                return ResourceManager.GetString("StrPageRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page Up.
        /// </summary>
        internal static string StrPageUp {
            get {
                return ResourceManager.GetString("StrPageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        internal static string StrRefresh {
            get {
                return ResourceManager.GetString("StrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Relative.
        /// </summary>
        internal static string StrRelative {
            get {
                return ResourceManager.GetString("StrRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rendering Options.
        /// </summary>
        internal static string StrRenderingOptions {
            get {
                return ResourceManager.GetString("StrRenderingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rendering Quality.
        /// </summary>
        internal static string StrRenderingQuality {
            get {
                return ResourceManager.GetString("StrRenderingQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retry.
        /// </summary>
        internal static string StrRetry {
            get {
                return ResourceManager.GetString("StrRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RFC 2822.
        /// </summary>
        internal static string StrRFC2822 {
            get {
                return ResourceManager.GetString("StrRFC2822", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right Edge.
        /// </summary>
        internal static string StrRightEdge {
            get {
                return ResourceManager.GetString("StrRightEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sample.
        /// </summary>
        internal static string StrSample {
            get {
                return ResourceManager.GetString("StrSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scroll Down.
        /// </summary>
        internal static string StrScrollDown {
            get {
                return ResourceManager.GetString("StrScrollDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scroll Here.
        /// </summary>
        internal static string StrScrollHere {
            get {
                return ResourceManager.GetString("StrScrollHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scroll Left.
        /// </summary>
        internal static string StrScrollLeft {
            get {
                return ResourceManager.GetString("StrScrollLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scroll Right.
        /// </summary>
        internal static string StrScrollRight {
            get {
                return ResourceManager.GetString("StrScrollRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scroll Up.
        /// </summary>
        internal static string StrScrollUp {
            get {
                return ResourceManager.GetString("StrScrollUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send Bugreport.
        /// </summary>
        internal static string StrSendBugreport {
            get {
                return ResourceManager.GetString("StrSendBugreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add &quot;Run gitter&quot; item to folder menu in Windows Explorer.
        /// </summary>
        internal static string StrsExplorerContextMenuFeature {
            get {
                return ResourceManager.GetString("StrsExplorerContextMenuFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download and show user avatars using gravatar.com.
        /// </summary>
        internal static string StrsGravatarDisplayText {
            get {
                return ResourceManager.GetString("StrsGravatarDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show.
        /// </summary>
        internal static string StrShow {
            get {
                return ResourceManager.GetString("StrShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simple.
        /// </summary>
        internal static string StrSimple {
            get {
                return ResourceManager.GetString("StrSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Integration features.
        /// </summary>
        internal static string StrsIntegrationFeatures {
            get {
                return ResourceManager.GetString("StrsIntegrationFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        internal static string StrSize {
            get {
                return ResourceManager.GetString("StrSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source.
        /// </summary>
        internal static string StrSource {
            get {
                return ResourceManager.GetString("StrSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spell Checking.
        /// </summary>
        internal static string StrSpelling {
            get {
                return ResourceManager.GetString("StrSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stack.
        /// </summary>
        internal static string StrStack {
            get {
                return ResourceManager.GetString("StrStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard.
        /// </summary>
        internal static string StrStandard {
            get {
                return ResourceManager.GetString("StrStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        internal static string StrStop {
            get {
                return ResourceManager.GetString("StrStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Strikeout.
        /// </summary>
        internal static string StrStrikeout {
            get {
                return ResourceManager.GetString("StrStrikeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Style.
        /// </summary>
        internal static string StrStyle {
            get {
                return ResourceManager.GetString("StrStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;{0}&quot;.
        /// </summary>
        internal static string StrSurroundWithDoubleQuotes {
            get {
                return ResourceManager.GetString("StrSurroundWithDoubleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;{0}&apos;.
        /// </summary>
        internal static string StrSurroundWithSingleQuotes {
            get {
                return ResourceManager.GetString("StrSurroundWithSingleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System Default.
        /// </summary>
        internal static string StrSystemDefault {
            get {
                return ResourceManager.GetString("StrSystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timestamp.
        /// </summary>
        internal static string StrTimestamp {
            get {
                return ResourceManager.GetString("StrTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top.
        /// </summary>
        internal static string StrTop {
            get {
                return ResourceManager.GetString("StrTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string StrType {
            get {
                return ResourceManager.GetString("StrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UI Font.
        /// </summary>
        internal static string StrUIFont {
            get {
                return ResourceManager.GetString("StrUIFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Underline.
        /// </summary>
        internal static string StrUnderline {
            get {
                return ResourceManager.GetString("StrUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UNIX Timestamp.
        /// </summary>
        internal static string StrUNIXTimestamp {
            get {
                return ResourceManager.GetString("StrUNIXTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Up.
        /// </summary>
        internal static string StrUp {
            get {
                return ResourceManager.GetString("StrUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text Viewer Font.
        /// </summary>
        internal static string StrViewerFont {
            get {
                return ResourceManager.GetString("StrViewerFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visible Columns.
        /// </summary>
        internal static string StrVisibleColumns {
            get {
                return ResourceManager.GetString("StrVisibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web Browser.
        /// </summary>
        internal static string StrWebBrowser {
            get {
                return ResourceManager.GetString("StrWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string StrYes {
            get {
                return ResourceManager.GetString("StrYes", resourceCulture);
            }
        }
    }
}
